### ISSUE TITLE
1.20.4

### ISSUE THREAD

**Issue by Coneman617** [matthewperiut/factory_blocks#11]
![image_2024-11-04_003915593](https://github.com/user-attachments/assets/e24c20d3-554c-475c-a22d-5b0c86c1e80e)
1.20.4 does not work it gives the error (at least on neo-forge this is the error I am getting)  factory blocks neo forge has been compiled by a more recent version of java runtime (class file version 65.0) this version of java runtime only recognizes class file versions up to 61.0

**Comment by matthewperiut** [comment]
I know this isn't an ideal solution but try running it with java 21

**Comment by Coneman617** [comment]
How?

**Comment by matthewperiut** [comment]
actually it's okay I'll provide a fixed download.

**Comment by Coneman617** [comment]
I downloaded off of cursed forge just letting you know and also thank you so much for fixing it I'm currently working on a space build and I realized I didn't have this installed and figured it would look really cool I am so sorry to literally submit an error report at like midnight

**Comment by matthewperiut** [comment]
I would've been up anyways! all good, just was about to go to the gym, but it's building right now, I'll have a download very soon.

**Comment by Coneman617** [comment]
Thank you for fixing this issue almost immediately factory blocks is one of my favorite mods because of well I like factories so thank you so much for fixing this

**Comment by matthewperiut** [comment]
usually the builds are a lot faster, this might be a minute, but I'll have a build for you to test and then I'll put it on curseforge and modrinth.

**Comment by Coneman617** [comment]
Kk

**Comment by matthewperiut** [comment]
[factory_blocks-1.3.1.jar.zip](https://github.com/user-attachments/files/17614246/factory_blocks-1.3.1.jar.zip)
The download is inside this zip if you could make sure this works

**Comment by matthewperiut** [comment]
oh yeah make sure you download chisel to use with it or chipped

**Comment by matthewperiut** [comment]
oh and also `athena` for connected textures lol rip

**Comment by Coneman617** [comment]
It's working!

**Comment by Coneman617** [comment]
Is it compatible with jei?

**Comment by matthewperiut** [comment]
It's compatible, but I specifically have EMI and REI implemented. but its no big deal just make a chest out of alternating iron and stone and then put it in the chisel and you'll see all the types of factory blocks

**Comment by Coneman617** [comment]
Alternating iron?

**Comment by Coneman617** [comment]
OH

**Comment by matthewperiut** [comment]
![2024-11-04_01 15 43](https://github.com/user-attachments/assets/282267e6-2895-437d-8f87-171bed9b5357)

**Comment by Coneman617** [comment]
I realized what you meant like 2 seconds after I sent that

**Comment by matthewperiut** [comment]
![2024-11-04_01 16 14](https://github.com/user-attachments/assets/8ad32f51-6dcc-4d24-a8d9-16a62ad2a7c3)

**Comment by matthewperiut** [comment]
![2024-11-04_01 16 32](https://github.com/user-attachments/assets/e6e8157d-7277-410b-a162-6bb81cf95db8)

**Comment by matthewperiut** [comment]
complete kit lol and all good!

**Comment by Coneman617** [comment]
yep it's 100% working thank you
