### ISSUE TITLE
Incorrect folder names for tags and loot tables

### ISSUE THREAD

**Issue by Saereth** [matthewperiut/factory_blocks#12]
factory_blocks-neoforge-1.3.3+mc1.21.1.jar
Neoforge
your folders for loot_tables and tags/blocks should be loot_table/blocks and tags/block now, same for minecraft/block
the s was dropped so currently the blocks arent mineable since they lack the tags and if you set the tags and mine them they drop nothing due to the invalid loot tables, should be a pretty simple fix though!

**Comment by matthewperiut** [comment]
thank you! will fix
