### ISSUE TITLE
Factory Blocks 1.1.0-1.20.1 requires Chisel 1.6.0-1.20.1 despite it being present

### ISSUE THREAD

**Issue by Delfite** [matthewperiut/factory_blocks#5]
![image](https://github.com/matthewperiut/factory_blocks/assets/23504262/579794f0-cd25-4c4f-b50f-76adb54db7ff)
The game says it's missing `Chisel 1.6.0-1.20.1`...
![image](https://github.com/matthewperiut/factory_blocks/assets/23504262/d0d5bc08-989b-4acc-9dc8-0aa3d7c41199)
![image](https://github.com/matthewperiut/factory_blocks/assets/23504262/0360f180-18fd-495e-a8a9-ba1956426946)
...despite Chisel 1.6.0 already being installed.

Log File: https://gnomebot.dev/paste/1176315649975386303

Note: This could possibly be an issue with the Connector mod that Chisel uses to translate it's code from Fabric to Forge, but I'm not 100% sure about it.

**Comment by matthewperiut** [comment]
Should be fixed on latest versions
