### ISSUE TITLE
Factory blocks missing sounds on 1.20.1

### ISSUE THREAD

**Issue by KingYamiJ** [matthewperiut/factory_blocks#7]
I playing on CurseForge Launcher (Fabric) (1.20.1).

I'm using presence footsteps with the mods and the Factory blocks doesn't make any sounds when you step or walk on them. only sounds for place/destroy is working,

The "Chisel Reborn" mod sounds for presence footsteps is working fine.

**Comment by KingYamiJ** [comment]
[Edit1 I think the problem is that the footstep sounds on the blocks are set very low. I did a test with a friend and I can't hear my footsteps on the blocks, but I can hear a very low sound of him walking on the metal.

**Comment by matthewperiut** [comment]
I can't seem to reproduce, reopen if still an issue.
